# Generated by Django 2.2 on 2019-04-28 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=64, verbose_name='任务名称')),
                ('publisher', models.CharField(max_length=32, verbose_name='发布人')),
                ('receiver', models.CharField(max_length=32, null=True, verbose_name='领取人')),
                ('brokerage', models.FloatField(default=0, max_length=16, verbose_name='平台佣金')),
                ('service_fee', models.FloatField(max_length=16, verbose_name='个人佣金')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='任务创建时间')),
                ('first_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='任务领取时间')),
                ('last_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='任务结束时间')),
                ('get_status', models.IntegerField(choices=[(0, '待领取'), (1, '已领取')], default=0, verbose_name='任务领取状态')),
                ('completion_status', models.IntegerField(choices=[(0, '未完成'), (1, '已完成'), (2, '任务失败')], default=0, verbose_name='任务完成状态')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '妖')], default=3, verbose_name='性别')),
                ('birthday', models.DateTimeField(default=django.utils.timezone.now, verbose_name='用户生日')),
                ('school', models.CharField(max_length=64, null=True, verbose_name='学校')),
                ('major', models.CharField(max_length=64, null=True, verbose_name='专业')),
                ('tel', models.CharField(max_length=64, null=True, verbose_name='电话')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=True, to='api.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='User_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='用户注册日期')),
                ('user', models.OneToOneField(on_delete=True, to='api.UserInfo')),
            ],
        ),
    ]
